version: '3'

services:
    spark:
        image: gettyimages/spark:2.4.0-hadoop-3.0
        container_name: spark
        expose:
            - 4040
        ports:
            - 4040:4040
        volumes:
            - ./:/appdata

