version: '3'

services:
    spark:
        build: .
        container_name: spark
        expose:
            - 4040
        ports:
            - 4040:4040
        network_mode: "host"
        environment:
            SPARK_PUBLIC_DNS: localhost

